### ISSUE TITLE
Ask Command Bugssss :((((

### ISSUE THREAD

**Issue by Mervinpais** [Mervinpais/FreeCode---Be-Free-To-Code#8]
2-3 bugs with the "ask" statement that I cant even explain since they are sooooo long :/

One bug is when you try both a "say" and "ask" and the ask will not work

**Comment by Sh3rwinTheYoungCoder** [comment]
in the new updat, its now fixed, can you close this issue @Mervinpais

**Comment by Mervinpais** [comment]
ok, im closing this now
